all: Calculator.class CalculatorImpl.class MyClient.class PiServer.class Start.class

Calculator.class:
	javac Schrack/Calculator.java

CalculatorImpl.class:
	javac Schrack/CalculatorImpl.java

MyClient.class:
	javac Schrack/MyClient.java

PiServer.class:
	javac Schrack/PiServer.java

Start.class:
	javac Schrack/Start.java

clean:
	rm Schrack/Calculator.class Schrack/CalculatorImpl.class Schrack/MyClient.class Schrack/PiServer.class Schrack/Start.class


